name: Container
on: push

jobs:
  voicevox-docker:
    runs-on: ubuntu-latest
    container:
      image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
      ports:
        - 50021:50021
    steps:
      - name: Copy README.md to container
        run: docker cp README.md $(docker ps -q):/tmp
      - name: Display README.md in container
        run: |
          echo "Contents of README.md:"
          docker exec $(docker ps -q) cat /tmp/README.md
