name: Voicevox Engine
on:
  push:
    branches:
      - main
      
jobs:
  voicevox-engine:
    runs-on: ubuntu-latest
    container: #起動するコンテナイメージを指定
      image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest #指定のdockerイメージを使用
    ports:
      - '50021:50021'
    steps: #dockerコンテナ内でステップを実行
      - name: Check Voicevox Engine version
        run: |
          voicevox_engine --version #Voicevox Engineバージョンの確認
