name: Container
on: push

jobs:
  voicevox-docker:
    runs-on: ubuntu-20.04
    container:
      image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
      ports:
        - 50021:50021
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python
        run: |
          apt update
          apt install python3 python-pip3 -y
          pip3 install requests json pydub natsort
          python3 ./weather.py
          ls -l
